'use strict';
const VERSION='1.4';
const AUDIT_ONLY_TAGS=new Set(['Modification date','Last modified by']);
const UNORDERED_REFERENCE_TAGS=new Set(['RefinedBy','SatisfiedBy']);
const DEDUPE_REFERENCE_TAGS=new Set(['Extension']);
const EMBEDDED_ID_TAGS=new Set(['rowElements','rowsOrder','columnCollapsedNodes','rowCollapsedNodes','expandedRows','location','dependencyCriteria']);
const CONFIG_FIELDS=['schemaVersion','scope','scanMode','attachedProjectContentExcluded','comparisonIdStrategy'];
const ENV_FIELDS=['schemaVersion','generator','generatedUtc','magicDrawOpenApiVersion','javaVersion','javaSpecificationVersion','javaRuntimeVersion','javaVendor','javaVmName','javaVmVersion','groovyVersion','osName','osArch','osVersion'];
const SUMMARY_METRICS=[
  ['elementCount','Elements','element'],['propertyCount','Properties','property'],['relationshipCount','Relationships','relationship'],['connectorCount','Connectors','connector'],
  ['taggedValueCount','Tagged values','tagged'],['appliedStereotypeOccurrenceCount','Stereotype applications','stereotype'],
  ['diagramCount','Diagrams','diagramExistence'],['__diagramContent__','Diagram content','diagramChanged'],['scannedGhostProxyCount','Unresolved model references','ghostProxy']
];
const state={baseline:null,candidate:null,baselineFile:null,candidateFile:null,comparison:null,filters:{metric:'',category:'',property:'',metaclass:'',search:'',quick:'all'}};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=v=>Array.isArray(v)?v:[];
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v);
function stable(v){if(Array.isArray(v))return '['+v.map(stable).join(',')+']';if(obj(v))return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}';return JSON.stringify(v);}
function eq(a,b){return stable(a)===stable(b)}
function uniqueSorted(a){return [...new Set(a)].sort((x,y)=>String(x).localeCompare(String(y)))}
function projectName(fp){return String(fp?.project?.name||'')}
function primaryModelKey(fp){const pm=fp?.project?.primaryModel;return obj(pm)?String(pm.key||pm.id||''):String(pm||'')}
function schemaMajor(v){return String(v||'').split('.')[0]}
function validateFingerprint(fp){const e=[];if(!fp||typeof fp!=='object')return ['JSON root is not an object.'];if(schemaMajor(fp.schemaVersion)!=='1')e.push(`Unsupported fingerprint schema '${fp.schemaVersion??''}'.`);if(!Array.isArray(fp.elements))e.push("Missing 'elements' array.");if(!Array.isArray(fp.diagrams))e.push("Missing 'diagrams' array.");if(!obj(fp.summary))e.push("Missing 'summary' object.");return e}
function runtimeAssessment(fp,expected){const spec=String(fp?.javaSpecificationVersion||'');const java=String(fp?.javaVersion||'');const groovy=String(fp?.groovyVersion||'');const project=projectName(fp)||'<unnamed>';let ok=true,msg='';if(expected==='2022'){ok=spec==='11'||java.startsWith('11.');msg=ok?'Runtime is consistent with the expected 2022xR2 baseline.':'Warning: expected the 2022xR2 baseline runtime family (Java 11).';}else{ok=spec==='17'||java.startsWith('17.');msg=ok?'Runtime is consistent with the expected 2024xR3 candidate.':'Warning: expected the 2024xR3 candidate runtime family (Java 17).';}return {ok,msg,detail:`Project: ${project}<br>Java: ${esc(java||'<unknown>')} · Groovy: ${esc(groovy||'<unknown>')} · Schema: ${esc(fp?.schemaVersion||'<unknown>')}`}}
async function loadFile(input,side){const file=input.files?.[0];if(!file)return;$(side+'Name').textContent=file.name;$(side+'Status').innerHTML='Reading fingerprint…';try{const text=await file.text();const fp=JSON.parse(text);const errors=validateFingerprint(fp);if(errors.length)throw new Error(errors.join(' '));state[side]=fp;state[side+'File']=file;const a=runtimeAssessment(fp,side==='baseline'?'2022':'2024');$(side+'Status').innerHTML=`<div class="${a.ok?'oktxt':'warntxt'}">${esc(a.msg)}</div><div>${a.detail}</div>`;}catch(err){state[side]=null;state[side+'File']=null;$(side+'Status').innerHTML=`<span class="errtxt">${esc(err.message)}</span>`;}updateCompareButton()}
function updateCompareButton(){$('compareBtn').disabled=!(state.baseline&&state.candidate)}
function isInfrastructure(e){const mc=String(e?.metaclass||'').trim().toLowerCase();return mc==='profileapplication'||mc.endsWith('taggedvalue')}
function comparisonElements(records){const kept=[],ignored={};for(const e of arr(records)){if(isInfrastructure(e)){const mc=String(e.metaclass||'<unknown>');ignored[mc]=(ignored[mc]||0)+1}else kept.push(e)}return {kept,ignored}}
function looksRefMap(v){return obj(v)&&['key','qualifiedName','repositoryId','localId'].some(k=>k in v)&&('metaclass'in v)}
function normalizeRef(v,alias={}){if(v==null)return '';if(obj(v)){const qn=String(v.qualifiedName||'');if(qn)return 'qname:'+qn;const name=String(v.name||''),mc=String(v.metaclass||'');if(name)return `name:${mc}:${name}`;const key=String(v.key||'');if(key)return normalizeRef(key,alias);const id=String(v.localId||v.id||'');return id?'id:'+(alias[id]||id):''}const text=String(v);if(text.startsWith('id:')){const raw=text.slice(3);return 'id:'+(alias[raw]||raw)}return text}
function normalizeEmbeddedIds(text,alias={}){if(!text||!Object.keys(alias).length)return text;return String(text).replace(/\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b/g,m=>alias[m]||m).replace(/(^|[^A-Za-z0-9])(_[A-Za-z0-9]+(?:_[A-Za-z0-9]+){2,})(?![A-Za-z0-9])/g,(m,p,id)=>p+(alias[id]||id))}
function xmlLocalName(s){s=String(s||'');if(s.includes('}'))s=s.split('}').pop();if(s.includes(':'))s=s.split(':').pop();return s}
function looksXml(v){return typeof v==='string'&&(/^\s*<\?xml/.test(v)||/^\s*</.test(v))}
function structuredExpressionSemantic(value){if(!looksXml(value))return null;try{const doc=new DOMParser().parseFromString(String(value).trim(),'application/xml');if(doc.querySelector('parsererror'))return null;function clean(el){const tag=xmlLocalName(el.tagName);if(tag==='entry'&&String(el.getAttribute('key')||'')==='pathIcon')return null;const attrs={};[...el.attributes].sort((a,b)=>xmlLocalName(a.name).localeCompare(xmlLocalName(b.name))).forEach(a=>{const k=xmlLocalName(a.name);if(k!=='stereotype'&&k!=='element')attrs[k]=a.value});const children=[...el.children].map(clean).filter(Boolean);const directText=[...el.childNodes].filter(n=>n.nodeType===3).map(n=>n.nodeValue.trim()).filter(Boolean).join(' ');const out={tag};if(Object.keys(attrs).length)out.attrs=attrs;if(directText)out.text=directText;if(children.length)out.children=children;return out}return clean(doc.documentElement)}catch{return null}}
function normalizeValue(v,alias={}){if(obj(v)){if(looksRefMap(v))return normalizeRef(v,alias);const out={};Object.keys(v).sort().forEach(k=>out[k]=normalizeValue(v[k],alias));return out}if(Array.isArray(v))return v.map(x=>normalizeValue(x,alias));if(typeof v==='string'){if(v.startsWith('id:'))return normalizeRef(v,alias);if(alias[v])return 'id:'+alias[v]}return v}
function normalizeStereotypes(v,alias={}){return arr(v).map(x=>normalizeRef(x,alias)).sort()}
function dedupePreserve(values){const out=[],seen=new Set();for(const v of values){const k=stable(v);if(!seen.has(k)){seen.add(k);out.push(v)}}return out}
function normalizeTagPayload(def,value,alias={}){let v=normalizeValue(value,alias);if(EMBEDDED_ID_TAGS.has(def)){const walk=x=>{if(typeof x==='string'){const n=normalizeEmbeddedIds(x,alias);if(def==='dependencyCriteria'){const sem=structuredExpressionSemantic(n);if(sem)return sem}return n}if(Array.isArray(x))return x.map(walk);if(obj(x)){const o={};for(const[k,val]of Object.entries(x))o[k]=walk(val);return o}return x};v=walk(v)}if(def==='dependencyCriteria'&&Array.isArray(v)){const m=new Map(v.map(x=>[stable(x),x]));v=[...m.keys()].sort().map(k=>m.get(k))}if(UNORDERED_REFERENCE_TAGS.has(def)&&Array.isArray(v)){const m=new Map(v.map(x=>[stable(x),x]));v=[...m.keys()].sort().map(k=>m.get(k))}else if(DEDUPE_REFERENCE_TAGS.has(def)&&Array.isArray(v))v=dedupePreserve(v);return v}
function normalizeTaggedValues(v,alias={}){const grouped={};for(const item of arr(v)){let def,val;if(obj(item)){def=String(item.definitionName||item.definitionKey||'<unnamed-tag>');if(AUDIT_ONLY_TAGS.has(def))continue;val=normalizeTagPayload(def,item.value,alias)}else{def='<unknown>';val=normalizeValue(item,alias)}(grouped[def]??=[]).push(val)}const out={};Object.keys(grouped).sort().forEach(def=>{const vals=grouped[def].sort((a,b)=>stable(a).localeCompare(stable(b)));out[def]=vals.length===1?vals[0]:vals});return out}
function normalizeConnector(c,alias={}){if(!obj(c))return c;const ends=arr(c.ends).map(e=>obj(e)?{role:normalizeRef(e.role,alias),partWithPort:normalizeRef(e.partWithPort,alias),definingEnd:normalizeRef(e.definingEnd,alias),lower:e.lower??null,upper:e.upper??null}:normalizeValue(e,alias)).sort((a,b)=>stable(a).localeCompare(stable(b)));return {type:normalizeRef(c.type,alias),kind:c.kind??null,ends}}
function elementSemanticView(e,alias={}){let attrs=normalizeValue(e.persistentAttributes||{},alias);if(obj(attrs)){attrs={...attrs};if(attrs.visibility==='public')delete attrs.visibility;if(String(e.metaclass||'').toLowerCase()==='model')delete attrs.ID;if('body'in attrs){
  const normalizeBodyValue=x=>{
    if(typeof x!=='string')return x;
    const n=normalizeEmbeddedIds(x,alias);
    if(looksXml(n)){
      const sem=structuredExpressionSemantic(n);
      if(sem)return sem;
    }
    return n;
  };
  if(Array.isArray(attrs.body))attrs.body=attrs.body.map(normalizeBodyValue);
  else attrs.body=normalizeBodyValue(attrs.body)
}}const view={metaclass:e.metaclass||'',name:e.name||'',qualifiedName:e.qualifiedName||'',owner:normalizeRef(e.owner,alias),stereotypes:normalizeStereotypes(e.appliedStereotypes,alias),taggedValues:normalizeTaggedValues(e.taggedValues,alias),persistentAttributes:attrs,persistentReferences:normalizeValue(e.persistentReferences||{},alias),proxy:!!e.proxy,ghostProxy:!!e.ghostProxy};if('type'in e)view.type=normalizeRef(e.type,alias);if('multiplicity'in e)view.multiplicity=normalizeValue(e.multiplicity,alias);if('relationship'in e)view.relationship=normalizeValue(e.relationship,alias);if('connector'in e)view.connector=normalizeConnector(e.connector,alias);return view}
const elementId=e=>String(e?.id||e?.localId||'');
const elementKey=(e,i)=>elementId(e)?'id:'+elementId(e):`noid:${e?.qualifiedName||''}|${e?.metaclass||''}|${e?.name||''}|#${i}`;
const reconcileKey=e=>e?.qualifiedName?`${e.metaclass||''}|${e.qualifiedName}`:'';
const diagramId=d=>String(d?.id||'');
const diagramKey=(d,i)=>diagramId(d)?'id:'+diagramId(d):`noid:${d?.qualifiedName||''}|${d?.diagramType||''}|#${i}`;
const diagramReconcileKey=d=>d?.qualifiedName?`${d.diagramType||''}|${d.qualifiedName}`:'';
function indexRecords(records,keyFn){const map=new Map(),warnings=[];records.forEach((r,i)=>{const k=keyFn(r,i);if(map.has(k))warnings.push(`Duplicate comparison key '${k}'. The later record was retained.`);map.set(k,r)});return{map,warnings}}
function reconcileUnique(removed,added,keyFn){const bg=new Map(),cg=new Map();for(const r of removed){const k=keyFn(r);if(k)(bg.get(k)||bg.set(k,[]).get(k)).push(r)}for(const r of added){const k=keyFn(r);if(k)(cg.get(k)||cg.set(k,[]).get(k)).push(r)}const pairs=[],pb=new Set(),pc=new Set();for(const k of [...bg.keys()].filter(k=>cg.has(k)).sort()){if(bg.get(k).length===1&&cg.get(k).length===1){const b=bg.get(k)[0],c=cg.get(k)[0];pairs.push([b,c]);pb.add(b);pc.add(c)}}return{pairs,removed:removed.filter(r=>!pb.has(r)),added:added.filter(r=>!pc.has(r))}}
function buildAliases(b,c,reconciled){const c2b={};for(const[bv,cv]of reconciled){const bi=elementId(bv),ci=elementId(cv);if(bi&&ci)c2b[ci]=bi}const a={};for(const e of b){const canon=elementId(e);if(!canon)continue;for(const f of ['id','localId','repositoryId'])if(e[f])a[String(e[f])]=canon}for(const e of c){const ci=elementId(e),canon=c2b[ci]||ci;if(!canon)continue;for(const f of ['id','localId','repositoryId'])if(e[f])a[String(e[f])]=canon}return a}
const isRelationship=e=>obj(e)&&('relationship'in e);const isConnector=e=>obj(e)&&('connector'in e);const isProperty=e=>obj(e)&&String(e.metaclass||'').toLowerCase()==='property';
function structuralMetric(e){if(isRelationship(e))return'relationship';if(isConnector(e))return'connector';if(isProperty(e))return'property';return'element'}
function stereotypeLeaves(e){return arr(e?.appliedStereotypes).map(x=>{let t=obj(x)?String(x.qualifiedName||x.name||x.key||''):String(x||'');if(t.startsWith('qname:'))t=t.slice(6);return t.split('::').pop().trim()}).filter(Boolean)}
function propertyKind(e){if(!isProperty(e))return'';const c=[];if(e.humanType)c.push(String(e.humanType));c.push(...stereotypeLeaves(e));const mapping=[['partproperty','Part Property'],['valueproperty','Value Property'],['referenceproperty','Reference Property'],['constraintproperty','Constraint Property'],['flowproperty','Flow Property']];for(const text of c){const compact=text.toLowerCase().replace(/[^a-z0-9]/g,'');for(const[token,label]of mapping)if(compact.includes(token))return label}return'Property / Attribute'}
function objectKind(e){return propertyKind(e)||(isRelationship(e)?String(e.metaclass||'Relationship'):isConnector(e)?'Connector':String(e?.humanType||e?.metaclass||''))}
function metricKeysForElement(e,existence=false){const s=new Set();if(!obj(e)){if(existence)s.add('existence');return[...s].sort()}s.add(structuralMetric(e));if(existence)s.add('existence');if(isRelationship(e)&&obj(e.relationship)&&('source'in e.relationship||'target'in e.relationship))s.add('directedRelationship');if('type'in e)s.add('type');if('multiplicity'in e)s.add('multiplicity');if(arr(e.taggedValues).length)s.add('tagged');if(arr(e.appliedStereotypes).length)s.add('stereotype');if(e.proxy)s.add('proxy');if(e.ghostProxy)s.add('ghostProxy');return[...s].sort()}
function metricKeysForPath(path,e){const p=String(path||'').toLowerCase(),s=new Set();if(obj(e))s.add(structuralMetric(e));if(p==='existence')metricKeysForElement(e,true).forEach(x=>s.add(x));else if(p.startsWith('relationship')){s.add('relationship');if(isRelationship(e)&&obj(e.relationship)&&('source'in e.relationship||'target'in e.relationship))s.add('directedRelationship')}else if(p.startsWith('connector'))s.add('connector');else if(p.startsWith('type'))s.add('type');else if(p.startsWith('metaclass'))s.add('metaclass');else if(p.startsWith('multiplicity'))s.add('multiplicity');else if(p.startsWith('taggedvalues'))s.add('tagged');else if(p.startsWith('stereotypes'))s.add('stereotype');else if(p.startsWith('ghostproxy'))s.add('ghostProxy');else if(p.startsWith('proxy'))s.add('proxy');else if(p.startsWith('persistentattributes'))s.add('attribute');else if(p.startsWith('persistentreferences'))s.add('reference');else if(p.startsWith('owner'))s.add('ownership');else if(p==='name'||p==='qualifiedname')s.add('naming');else if(p==='localid')s.add('id');return[...s].sort()}
function metricKeysTransition(path,b,c){return uniqueSorted([...metricKeysForPath(path,b),...metricKeysForPath(path,c)])}
function deepDiff(b,c,path=''){if(eq(b,c))return[];if(obj(b)&&obj(c)){const out=[];for(const k of uniqueSorted([...Object.keys(b),...Object.keys(c)])){const p=path?path+'.'+k:k;if(!(k in b))out.push([p,'<missing>',c[k]]);else if(!(k in c))out.push([p,b[k],'<missing>']);else out.push(...deepDiff(b[k],c[k],p))}return out}if(Array.isArray(b)&&Array.isArray(c))return[[path||'value',b,c]];return[[path||'value',b,c]]}
function classify(path,objectType='Element'){const p=String(path).toLowerCase();if(p==='localid')return['REVIEW','Local ID'];if(objectType==='Diagram')return['FAIL','Diagram'];if(p==='existence')return['FAIL','Existence'];if(p.startsWith('ghostproxy')||p.startsWith('proxy'))return['FAIL','Proxy'];if(p.startsWith('metaclass')||p.startsWith('type'))return['FAIL','Identity / Type'];if(p.startsWith('owner'))return['FAIL','Ownership'];if(p.startsWith('stereotypes'))return['FAIL','Stereotype'];if(p.startsWith('taggedvalues'))return['FAIL','Tagged Value'];if(p.startsWith('relationship'))return['FAIL','Relationship'];if(p.startsWith('connector'))return['FAIL','Connector'];if(p.startsWith('multiplicity'))return['FAIL','Multiplicity'];if(p.startsWith('persistentattributes'))return['FAIL','Persistent Attribute'];if(p.startsWith('persistentreferences'))return['FAIL','Persistent Reference'];if(p.startsWith('name')||p.startsWith('qualifiedname'))return['FAIL','Naming'];return['FAIL','Semantic']}
function recordDiff(out,o){let status=o.status,category=o.category;if(!status||!category){const a=classify(o.path,o.objectType);status=status||a[0];category=category||a[1]}const {path,...rest}=o;out.push({...rest,status,category,property:path,metricKeys:uniqueSorted(o.metricKeys||metricKeysForPath(path)),relationshipContext:o.relationshipContext||null})}
function existenceCategory(e,added){const action=added?'Added':'Missing';if(isConnector(e))return`Connector ${action}`;if(isRelationship(e))return`Relationship ${action}`;if(isProperty(e))return`Property ${action}`;return`Element ${action}`}
function referenceLabels(elements,alias){const out={};for(const e of elements){const label=String(e.qualifiedName||e.name||elementId(e)||'');if(!label)continue;for(const f of ['id','localId','repositoryId'])if(e[f])out['id:'+(alias[String(e[f])]||String(e[f]))]=label;if(e.qualifiedName)out['qname:'+e.qualifiedName]=e.qualifiedName}return out}
function prettyRef(v,labels){const t=String(v||'');if(labels[t])return labels[t];if(t.startsWith('qname:'))return t.slice(6);if(t.startsWith('name:'))return t.split(':').slice(2).join(':');return t}
function relationshipContext(e,alias,labels){if(!isRelationship(e))return null;const rel=normalizeValue(e.relationship||{},alias);if(!obj(rel))return null;const stereos=normalizeStereotypes(e.appliedStereotypes,alias).map(s=>prettyRef(s,labels).split('::').pop()).filter(Boolean);return{metaclass:String(e.metaclass||'Relationship'),stereotypes:stereos,directed:!!(arr(rel.source).length||arr(rel.target).length),source:arr(rel.source).map(x=>prettyRef(x,labels)),target:arr(rel.target).map(x=>prettyRef(x,labels)),related:arr(rel.related).map(x=>prettyRef(x,labels))}}
