function renderAll(){const c=state.comparison;if(!c)return;$('results').classList.remove('hidden');const badge=$('overallBadge');badge.textContent=c.overallResult;badge.className='overall-badge '+c.overallResult;$('overallText').textContent=`${c.baselineProject||'Baseline'} → ${c.candidateProject||'Candidate'} · ${c.differenceCount} normalized finding row${c.differenceCount!==1?'s':''}.`;renderWarnings(c);renderSummary(c.summaryRows);populateFilters(c.differences);renderFindings();renderDiagnostics(c)}
function renderWarnings(c){const el=$('warnings');let h='';for(const w of c.warnings)h+=`<div class="notice"><strong>Warning:</strong> ${esc(w)}</div>`;for(const n of c.notes)h+=`<div class="notice note"><strong>Note:</strong> ${esc(n)}</div>`;el.innerHTML=h}
function fmtDelta(v){if(v==='—')return'—';if(typeof v==='number')return(v>0?'+':'')+v;return String(v??'')}
function renderSummary(rows){const tb=$('summaryTable').querySelector('tbody');tb.innerHTML=rows.map(r=>{const findings=r.findingCount?`<button class="finding-link" data-metric="${esc(r.filterKey)}" title="Show ${esc(r.metric)} findings">${r.findingCount}</button> <span class="subtle">${esc(r.findingText)}</span>`:'—';return`<tr><td><strong>${esc(r.metric)}</strong></td><td class="num">${esc(r.baseline)}</td><td class="num">${esc(r.candidate)}</td><td class="num">${esc(fmtDelta(r.delta))}</td><td>${findings}</td><td><span class="pill ${r.result.toLowerCase()}">${r.result}</span></td></tr>`}).join('');tb.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{state.filters={metric:b.dataset.metric,category:'',property:'',metaclass:'',search:'',quick:'all'};syncFilterControls();renderFindings();$('findingsPanel').scrollIntoView({behavior:'smooth'})})}
const METRIC_LABELS={element:'Elements',property:'Properties',relationship:'Relationships',connector:'Connectors',tagged:'Tagged values',stereotype:'Stereotype applications',diagramExistence:'Diagrams',diagramChanged:'Diagram content',ghostProxy:'Unresolved model references',type:'Type',multiplicity:'Multiplicity',attribute:'Persistent attributes',reference:'Model references',ownership:'Ownership',naming:'Naming',id:'Local ID',proxy:'Normal proxies',directedRelationship:'Directed relationships',diagram:'Diagram'};
function optionList(select,values,allLabel){select.innerHTML=`<option value="">${esc(allLabel)}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
function populateFilters(diffs){const metrics=uniqueSorted(diffs.flatMap(d=>arr(d.metricKeys))).map(k=>[k,METRIC_LABELS[k]||humanWords(k)]);const ms=$('metricFilter');ms.innerHTML='<option value="">All metrics</option>'+metrics.map(([k,l])=>`<option value="${esc(k)}">${esc(l)}</option>`).join('');optionList($('categoryFilter'),uniqueSorted(diffs.map(d=>d.category)),'All categories');optionList($('propertyFilter'),uniqueSorted(diffs.map(d=>d.property)),'All properties');optionList($('metaclassFilter'),uniqueSorted(diffs.map(d=>d.objectMetaclass).filter(Boolean)),'All metaclasses');syncFilterControls()}
function syncFilterControls(){$('metricFilter').value=state.filters.metric;$('categoryFilter').value=state.filters.category;$('propertyFilter').value=state.filters.property;$('metaclassFilter').value=state.filters.metaclass;$('searchFilter').value=state.filters.search}
function rowMatches(d){const f=state.filters;if(f.metric&&!arr(d.metricKeys).includes(f.metric))return false;if(f.category&&d.category!==f.category)return false;if(f.property&&d.property!==f.property)return false;if(f.metaclass&&d.objectMetaclass!==f.metaclass)return false;if(f.quick==='changed'&&!['changed','diagram-changed','diagram-content-added','diagram-content-removed','id-changed','diagram-id-changed'].includes(d.deltaKind))return false;if(f.quick==='missing'&&!['missing','diagram-missing'].includes(d.deltaKind))return false;if(f.quick==='added'&&!['added','diagram-added'].includes(d.deltaKind))return false;if(f.quick==='diagramChanged'&&!arr(d.metricKeys).includes('diagramChanged'))return false;if(f.quick==='fail'&&d.status!=='FAIL')return false;if(f.quick==='review'&&d.status!=='REVIEW')return false;if(f.search){const s=f.search.toLowerCase(),hay=[d.objectName,d.objectId,d.objectMetaclass,d.objectKind,d.property,d.category,managerValue(d.baseline),managerValue(d.candidate)].join(' ').toLowerCase();if(!hay.includes(s))return false}return true}
function relationshipContextHtml(ctx){if(!ctx)return'';const stereo=arr(ctx.stereotypes).length?` «${esc(ctx.stereotypes.join(', '))}»`:'';let line='';if(ctx.directed){line=`${arr(ctx.source).map(esc).join(', ')||'<unknown source>'} → ${arr(ctx.target).map(esc).join(', ')||'<unknown target>'}`}else if(arr(ctx.related).length)line=ctx.related.map(esc).join(' ↔ ');return`<div class="context"><strong>${esc(ctx.metaclass||'Relationship')}${stereo}</strong>${line?`<br>${line}`:''}</div>`}
function findingTitle(rows){const d=rows[0];let title=d.category;if(d.objectKind&&d.objectKind!==d.objectMetaclass)title=d.objectKind;return title}
function renderFindings(){
 const all=state.comparison?.differences||[],filtered=all.filter(rowMatches),groups=groupDifferences(filtered);
 const chips=[];
 if(state.filters.metric)chips.push(`Metric: ${METRIC_LABELS[state.filters.metric]||humanWords(state.filters.metric)}`);
 if(state.filters.category)chips.push(`Category: ${state.filters.category}`);
 if(state.filters.property)chips.push(`Property: ${friendlyProperty(state.filters.property)}`);
 if(state.filters.metaclass)chips.push(`Metaclass: ${state.filters.metaclass}`);
 if(state.filters.search)chips.push(`Search: ${state.filters.search}`);
 if(state.filters.quick!=='all')chips.push(`Filter: ${humanWords(state.filters.quick)}`);
 $('activeChips').innerHTML=chips.map(x=>`<span class="chip">${esc(x)}</span>`).join('');
 $('findingCounter').textContent=`${groups.size} object${groups.size!==1?'s':''} · ${filtered.length} displayed finding${filtered.length!==1?'s':''}`;
 if(!filtered.length){$('findingList').innerHTML='<div class="empty">No findings match the current filters.</div>';return}
 let h='';
 for(const rows of groups.values()){
   const d=rows[0],status=rows.some(x=>x.status==='FAIL')?'FAIL':'REVIEW';
   const tags=uniqueSorted(rows.flatMap(x=>arr(x.metricKeys))).filter(x=>!['element','property','relationship','connector'].includes(x)).slice(0,6).map(x=>`<span class="tag">${esc(METRIC_LABELS[x]||humanWords(x))}</span>`).join('');
   const actionTags=uniqueSorted(rows.map(x=>changeDescriptor(x).label)).slice(0,4).map(x=>`<span class="change-badge change-${esc(rows.find(r=>changeDescriptor(r).label===x)?changeDescriptor(rows.find(r=>changeDescriptor(r).label===x)).tone:'changed')}">${esc(x)}</span>`).join('');
   h+=`<details class="finding-card"><summary><span class="pill ${status.toLowerCase()}">${status}</span><span>${esc(d.objectName||d.objectId||'<unnamed>')}</span><span class="kind">${esc(d.objectKind||d.objectMetaclass||d.objectType)}</span><span class="meta">· ${rows.length} finding${rows.length!==1?'s':''}</span>${actionTags}${tags}</summary>${relationshipContextHtml(rows.find(x=>x.relationshipContext)?.relationshipContext)}<div style="overflow:auto"><table class="finding-table"><thead><tr><th>Category</th><th>Finding</th><th>Change</th><th>Baseline</th><th>Candidate</th></tr></thead><tbody>`;
   for(const r of rows){
     const[bm,cm]=managerPair(r.property,r.baseline,r.candidate);
     h+=`<tr><td>${esc(r.category)}</td><td><strong>${esc(friendlyProperty(r.property))}</strong><div class="meta">${esc(r.objectMetaclass||'')}</div></td><td>${changeBadgeHtml(r)}</td><td class="manager">${esc(bm)}</td><td class="manager">${esc(cm)}</td></tr>`;
     if(needsTech(r.property,r.baseline,r.candidate,bm,cm))
       h+=`<tr><td colspan="5"><details class="tech"><summary>Technical details</summary><div class="meta">Raw property: ${esc(r.property)} · Object ID: ${esc(r.objectId)} · Delta metadata: ${esc(r.deltaKind||'changed')}</div><div class="raw"><strong>Baseline</strong>\n${esc(stable(r.baseline))}\n\n<strong>Candidate</strong>\n${esc(stable(r.candidate))}</div></details></td></tr>`;
   }
   h+='</tbody></table></div></details>';
 }
 $('findingList').innerHTML=h
}
function renderDiagnostics(c){const d=c.diagnostics,b=d.baselineTechnicalMetrics||{},x=d.candidateTechnicalMetrics||{},keys=uniqueSorted([...Object.keys(b),...Object.keys(x)]);let h='<h3>Technical inventory</h3><table><thead><tr><th>Metric</th><th class="num">Baseline</th><th class="num">Candidate</th></tr></thead><tbody>'+keys.map(k=>`<tr><td>${esc(k)}</td><td class="num">${esc(b[k]??'')}</td><td class="num">${esc(x[k]??'')}</td></tr>`).join('')+'</tbody></table>';h+='<h3>Property classification</h3>';const pk=uniqueSorted([...Object.keys(d.baselinePropertyKinds||{}),...Object.keys(d.candidatePropertyKinds||{})]);h+='<table><thead><tr><th>Property kind</th><th class="num">Baseline</th><th class="num">Candidate</th></tr></thead><tbody>'+pk.map(k=>`<tr><td>${esc(k)}</td><td class="num">${esc(d.baselinePropertyKinds?.[k]||0)}</td><td class="num">${esc(d.candidatePropertyKinds?.[k]||0)}</td></tr>`).join('')+'</tbody></table>';h+=`<p class="subtle">Ignored MagicDraw storage objects: baseline ${d.baselineIgnoredInfrastructureCount||0}, candidate ${d.candidateIgnoredInfrastructureCount||0}. Raw hash-only mismatches ignored: elements ${d.elementRawHashOnlyMismatchesIgnored||0}, diagrams ${d.diagramRawHashOnlyMismatchesIgnored||0}.</p>`;$('diagnostics').innerHTML=h}
function setProgress(p,msg){$('progress').classList.remove('hidden');$('progressBar').style.width=p+'%';$('statusLine').textContent=msg}
async function doCompare(){try{$('compareBtn').disabled=true;setProgress(15,'Validating fingerprints…');await new Promise(r=>setTimeout(r,20));const eb=validateFingerprint(state.baseline),ec=validateFingerprint(state.candidate);if(eb.length||ec.length)throw new Error([...eb,...ec].join(' '));setProgress(35,'Normalizing model content…');await new Promise(r=>setTimeout(r,20));state.comparison=buildComparison(state.baseline,state.candidate);setProgress(90,'Rendering report…');state.filters={metric:'',category:'',property:'',metaclass:'',search:'',quick:'all'};renderAll();setProgress(100,'Comparison complete.');setTimeout(()=>$('progress').classList.add('hidden'),500)}catch(e){$('statusLine').innerHTML=`<span class="errtxt">${esc(e.message)}</span>`;console.error(e)}finally{updateCompareButton()}}
function reset(){state.baseline=state.candidate=state.baselineFile=state.candidateFile=state.comparison=null;state.filters={metric:'',category:'',property:'',metaclass:'',search:'',quick:'all'};$('baselineFile').value=$('candidateFile').value='';$('baselineName').textContent=$('candidateName').textContent='No file selected';$('baselineStatus').textContent='Waiting for the 2022xR2 baseline fingerprint.';$('candidateStatus').textContent='Waiting for the 2024xR3 candidate fingerprint.';$('results').classList.add('hidden');$('statusLine').textContent='';$('progress').classList.add('hidden');updateCompareButton()}
function download(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function safeName(s){return String(s||'fingerprint').replace(/[\\/:*?"<>|\s]+/g,'_').replace(/^_+|_+$/g,'').slice(0,70)||'fingerprint'}
function baseOutputName(){return `${safeName(state.comparison?.baselineProject||'Baseline')}_vs_${safeName(state.comparison?.candidateProject||'Candidate')}`}
function csvCell(v){const s=typeof v==='string'?v:stable(v);return'"'+s.replace(/"/g,'""')+'"'}
function exportCsv(){const rows=[['Status','Category','Object Type','Object ID','Object Name','Object Kind','Metaclass','Finding','Change','Change Detail','Baseline','Candidate']];for(const d of state.comparison.differences){const[b,c]=managerPair(d.property,d.baseline,d.candidate),ch=changeDescriptor(d);rows.push([d.status,d.category,d.objectType,d.objectId,d.objectName,d.objectKind,d.objectMetaclass,friendlyProperty(d.property),ch.label,ch.detail,b,c])}download(baseOutputName()+'_UAT_Findings.csv',rows.map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8')}
function exportJson(){download(baseOutputName()+'_UAT_Comparison.json',JSON.stringify(state.comparison,null,2),'application/json;charset=utf-8')}
function staticReportHtml(){const c=state.comparison;const summary=$('summaryTable').outerHTML;let findings='';for(const d of c.differences){const[bm,cm]=managerPair(d.property,d.baseline,d.candidate),ch=changeDescriptor(d);findings+=`<tr><td>${esc(d.status)}</td><td>${esc(d.objectName)}</td><td>${esc(d.objectKind||d.objectMetaclass)}</td><td>${esc(friendlyProperty(d.property))}</td><td><b>${esc(ch.label)}</b><br><small>${esc(ch.detail)}</small></td><td><pre>${esc(bm)}</pre></td><td><pre>${esc(cm)}</pre></td></tr>`}return`<!doctype html><meta charset="utf-8"><title>${esc(baseOutputName())} UAT Report</title><style>body{font:14px system-ui;margin:32px;color:#17202a}table{border-collapse:collapse;width:100%}th,td{border:1px solid #bbb;padding:8px;vertical-align:top;text-align:left}th{background:#eee}pre{white-space:pre-wrap;margin:0}.PASS{color:green}.FAIL{color:#a00}small{color:#555}</style><h1>MagicDraw Migration UAT Report</h1><p><b>Baseline:</b> ${esc(c.baselineProject)} — expected MagicDraw 2022xR2<br><b>Candidate:</b> ${esc(c.candidateProject)} — expected MagicDraw 2024xR3</p><h2>Overall result: ${esc(c.overallResult)}</h2><h2>Acceptance summary</h2>${summary}<h2>Detailed findings</h2><table><thead><tr><th>Status</th><th>Object</th><th>Kind</th><th>Finding</th><th>Change</th><th>Baseline</th><th>Candidate</th></tr></thead><tbody>${findings}</tbody></table><p>Generated ${esc(c.generatedUtc)} by Browser Comparator ${VERSION}.</p>`}
function exportHtml(){download(baseOutputName()+'_UAT_Report.html',staticReportHtml(),'text/html;charset=utf-8')}
$('baselineFile').addEventListener('change',e=>loadFile(e.target,'baseline'));$('candidateFile').addEventListener('change',e=>loadFile(e.target,'candidate'));$('compareBtn').onclick=doCompare;$('resetBtn').onclick=reset;$('exportCsvBtn').onclick=exportCsv;$('exportJsonBtn').onclick=exportJson;$('exportHtmlBtn').onclick=exportHtml;$('printBtn').onclick=()=>window.print();
for(const id of ['metricFilter','categoryFilter','propertyFilter','metaclassFilter'])$(id).onchange=e=>{state.filters[id.replace('Filter','')]=e.target.value;renderFindings()};$('searchFilter').oninput=e=>{state.filters.search=e.target.value;renderFindings()};document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{state.filters.quick=b.dataset.quick;renderFindings()});$('expandBtn').onclick=()=>document.querySelectorAll('.finding-card').forEach(x=>x.open=true);$('collapseBtn').onclick=()=>document.querySelectorAll('.finding-card').forEach(x=>x.open=false);
